### ISSUE TITLE
Experiment: Moving to goreleaser

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#481]
/assign

Trying to figure out if moving to goreleaser would result in net negative scripts to maintain. It might come at a cost of not having a `hack/make-binary.sh` that only builds the current GOOS/GOARCH (and always builds tarballs). But worth trying.

/kind proposal

**Comment by ahmetb** [comment]
It seemed promising, but I have encountered several blockers along the way. I'll keep this comment up-to-date with blockers.

- [ ] It seems the "signature" files (which I use to create our .sha256 files) aren't being created https://github.com/goreleaser/goreleaser/issues/1319 

    > Since this is so hacky, we might move to a single "checksums.txt" file which is supported out-of-the-box by Goreleaser. Currently the `*.sha256` files we have aren't utilized much anyway. The reason we have them is for auditability (comparing checksums to what's in Krew yaml).

- [ ] It does not seem possible to have [hooks](https://goreleaser.com/hooks/) for   events like pre-"archive", pre-"release".

   - Pre-archive hook: Reset stat timestamps of all binaries and LICENSE files for reproducible tarballs/zips
   - Pre-release hook: (1) move `krew.exe` to root of `dist/` to make it a release artifact on GitHub (2) populate `krew.yaml` template with checksums of tarball/zip artifacts created in "archive" step

- [ ] It does not seem possible to upload non-archive release artifacts. https://github.com/goreleaser/goreleaser/issues/1320 This would be used to upload extra files such as `krew.exe` and `krew.yaml` –but as far as I can tell, additional files cannot be added to the release.

- [x] GoReleaser supports custom release notes.

- [ ] Non-blocking: Majority of the Goreleaser documentation is currently inaccessible (https://github.com/goreleaser/goreleaser/issues/1318)

- [ ] GoReleaser cannot build binary for 1 OS/arch for dev purposes (equivalent of today's `hack/make-binary.sh`). Dev commands like `goreleaser --snapshot` will still build all os/arch combinations specified in the config file for a full release.

- [ ] GoReleaser cannot build "just binaries" and skip other stuff like creating tarball archives as it doesn't have a `--skip-archive` option. Right now we have `hack/make-binaries.sh` and `hack/make-release-artifacts.sh` separate (and a `hack/make-all.sh` to do both). If we lose this ability, you'll need to have a beefy machine to iterate on builds.

Again, I'll try my best to keep the list above up-to-date.
But right now there are many blockers to adopt GoReleaser.

**Comment by corneliusweig** [comment]
Honestly, I don't see much value in pursuing this any time soon. You have shown quite a few disadvantages of goreleaser over our current build scripts.

Our scripts are quite stable and we can customize them when need be. I have some doubts this would be easily possible with goreleaser.

**Comment by ahmetb** [comment]
Opened some more issues on goreleaser side, updated my comment above.
I'll follow up this in the background as the situation progresses
