### ISSUE TITLE
Set up website hosting

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#515]
To run a website at `krew.sigs.k8s.io` we need some process set up. Looking for volunteers to help with some tasks. 

We can follow the footsteps of kind.sigs.k8s.io for any of the following tasks.

- [x] Netlify site request from Kubernetes account (https://github.com/kubernetes/org/issues/1668):<br> https://kubernetes-sigs-krew.netlify.com
- [x] Get DNS records provisioned for the domain to point to Netlify (https://github.com/kubernetes/k8s.io/issues/614)
- [x] Add custom domain to Netlify (+figure out TLS certs) (https://app.netlify.com/sites/kubernetes-sigs-krew/settings)
- [x] Get Netlify to auto-build/publish when the ./site is updated (or always)
- [x] Get Netlify preview bot to kick in on pull requests changing ./site directory.

     ![image](https://user-images.githubusercontent.com/159209/75581520-7f54bd00-5a1e-11ea-8b3c-b78fbf0a4e4a.png)

- [x] Get Netlify build to ignore/skip if ./site is not changed. – Netlify automatically does this based on `base` path configured in netlify.toml:

      6:02:51 PM: No changes detected in base directory. Returning early from build.

- [x] Move documentation out of repo README.md (and other various markdown pages) to ./site/content, and link to the website. (#522 )

- [x] Ensure Netlify Preview sites aren't indexed by search engines (#524).

**Comment by corneliusweig** [comment]
@BenTheElder you probably know best how web hosting was set up for kind.sigs.k8s.io. Can you point us in the right direction?

**Comment by ahmetb** [comment]
Shame on me for thinking this is like a one-off thing that's rarely done.
But there's a clean process doc: https://github.com/kubernetes/community/blob/master/github-management/subproject-site-requests.md

**Comment by BenTheElder** [comment]
:wave: sorry for the late reply, yes @mrbobbytables was very kind to write this up into a proper process doc, I can't believe I forgot this! thanks again :heart:
