### ISSUE TITLE
Implement custom plugin indexes

### ISSUE THREAD

**Issue by chriskim06** [kubernetes-sigs/krew#566]
Here's a list of some of the remaining work regarding support for multiple indexes:
- [x] update `krew list` to work with multi-index (#560)
- [x] update `krew info` to work with multi-index (#563)
- [x] update `krew search` to work with multi-index (#574)
- [x] update `krew upgrade` to work with multi-index (#594)
- [x] update `krew update` to work with multi-index (#588)
- [x] ~~update `krew install` to work with multi-index~~ (no work needed?)
- [x] update `krew remove` to work with multi-index (#579)
- [x] implement `krew index add|remove|list` commands (#537, #545, #552)
- [x] refactor the code that shows updated/new plugins during update to also show index (#593)
- [x] cleanup issues (#562, #565, #625)
- [x] revisit `--help` messages to ensure examples reflect index/ syntax where applicable (#597)
- [x] discuss a strategy for index directory layout migration (#600)
- [x] rethink how the "local plugin index is not initialized" message should read, or how we suggest users to add krew-index if there are no indexes? (#595)
- [x] write integration tests (like `receiptsmigration`) to ensure index migration happens v0.3.4 -> x (#621)
- [x] revisit commands to ensure they can cope with an unreachable index (or an index w/ malformed yaml) (#614)
- [x] remove multi-index feature flag (#624)
- [x] update user guide to add documentation on custom plugin indexes (#618)
- [x] update developer guide to add documentation on hosting custom plugin indexes + what to pay attention to (#618)
- [x] define trust model for custom indexes for users (#576, #615)
- [x] make multi-index docs "not draft"
- [x] tag a new release
- [x] find solution to krew’s own first-time installation being "detached"

Proposal issue: #483
Proposal doc: [link](https://docs.google.com/document/d/1Im5gmBA6yuKRWgJWbaBjTTFNvkH0me05V3wEeNPU7fE/edit)

/area multi-index

**Comment by ahmetb** [comment]
I'm scratching off these two for now as I see no work necessary there. 

>  ~update `krew install` to work with multi-index~ (no work needed?)
>  ~update `krew remove` to work with multi-index~ (no work needed?)

"install" already works (correct me if I'm wrong), and "remove" has no notion of indexes (as it does not need to).

**Comment by chriskim06** [comment]
There was a small change required for install that was taken care of [here](https://github.com/kubernetes-sigs/krew/pull/555/files#diff-545a923cbe516bf9f1a2ff693259e8a6R102). As for uninstall, that might still be pending. If we want to support `krew uninstall foo/plugin` that'll require a small change.

**Comment by corneliusweig** [comment]
I think what @chriskim06 is referring to is that plugins installed via `--manifest` now set a `detached` index name. I don't think this is worth mentioning though, because it only affects plugin developers and the change is primarily cosmetic.

On the other hand, the uninstall question is still pending so let's not tick it off :)

**Comment by chriskim06** [comment]
Sorry I should have been more explicit (also when I click the link I added it doesn't take me to the line that I linked, I have to scroll up a bit for some reason), I was referring more to how a plugin is loaded when its being installed: `indexscanner.LoadPluginByName(paths.IndexPluginsPath(indexName), pluginName)`. We used to have `indexscanner.LoadPluginByName(paths.IndexPluginsPath(constants.DefaultIndexName), pluginName)` so things could only be installed from the default index until the arg passed to `IndexPluginsPath` was changed to use the index name passed by the user.

But this is pretty minor, tbh I don't even remember adding those 2 to this list :sweat_smile: so I think its totally fine to not include the install one on the list.

**Comment by ahmetb** [comment]
> But this is pretty minor, tbh I don't even remember adding those 2 to this list 😅

I'm editing the list above as we go. :)

**Comment by ahmetb** [comment]
@chriskim06 I've checked off a few recently completed items above. Please take a look if we're up to date.

**Comment by chriskim06** [comment]
So I linked your most recent PR to this bullet:
>  rethink how the "local plugin index is not initialized" message should read, or how we suggest users to add krew-index if there are no indexes?

Does that seem reasonable to check off since that was merged or did you have something else in mind?

**Comment by chriskim06** [comment]
@ahmetb for this bullet:
> write integration tests (like receiptsmigration) to ensure index migration happens v0.3.4 -> x

did you mean something like the [verify-receipts-upgrade-migration.sh]( write integration tests (like receiptsmigration) to ensure index migration happens v0.3.4 -> x) step of the ci workflow or just like standard cmd line integration tests?

**Comment by ahmetb** [comment]
Yeah similar to that script. We'd install old krew, install a couple of plugins, and then run the binary compiled as part of the build. Upon doing so, we verify (1) .krew/index/default/ exists (2) "krew index list" cmd works. 

Don't spend too much effort, as these are temporary. (Btw if we removed receipsmigration, we should remove that test, too)

**Comment by chriskim06** [comment]
Sounds good. I'll try to get to that soon. And ya I removed that script and the step in the ci

**Comment by ahmetb** [comment]
/close
N I C E

**Comment by corneliusweig** [comment]
Great work @chriskim06! Thanks for pushing `krew` forward. 🍾
